### PR TITLE
Fix #4152, use separate state for collection info panel and collection selection dialog

### LINKED ISSUE #4152: Link to collection disappears when clicking "Show Collection"
I'm having trouble understanding the intended behavior of Mirador when it comes to browsing collections. The following steps seem like a bug to me.

Steps to reproduce:

1. Go to https://projectmirador.org/embed/?iiif-content=https://iiif.io/api/cookbook/recipe/0032-collection/collection.json
2. Click on "Show Collection"
3. Open the first item in the collection: "The Gulf Stream"
4. Click on the hamburger menu in the top-left to "Toggle Sidebar"
5. In the sidebar, there is a subsection for the collection: "Simple Collection Example" with a "Show Collection" button.
6. If you click on that "Show Collection" button, this subsection disappears from the sidebar.
7. If you click "Close" on the collection dialog in the center of the screen, you have no way of getting back to the collection. The "Simple Collection Example" that was previously present in the sidebar is now gone, and it's impossible to get it back.

I can't imagine why this would be intended behavior. Why does the "Simple Collection Example" disappear from the sidebar when you click on "Show Collection"? If you select an item from the collection in the center dialog, it will come back, but not if you click "Close", which puts you in a strange state where the collection is now inaccessible.

### PR DESCRIPTION
**Pull request by lutzhelm**
Replacement for PR #4154; addresses problems mentioned in [this comment](https://github.com/ProjectMirador/mirador/pull/4154#issuecomment-2949717883).

### CODE REVIEW

File: src/components/CollectionDialog.jsx [hunk 1]
```diff
@@ -97,10 +97,10 @@ export function CollectionDialog({
   const selectManifest = (m) => {
     if (windowId) {
       updateWindow(windowId, {
-        canvasId: null, collectionPath: [...collectionPath, manifestId], manifestId: m.id,
+        canvasId: null, collectionPath: [...dialogCollectionPath, manifestId], manifestId: m.id,
       });
     } else {
-      addWindow({ collectionPath: [...collectionPath, manifestId], manifestId: m.id });
+      addWindow({ collectionPath: [...dialogCollectionPath, manifestId], manifestId: m.id });
```
Comment (lutzhelm) [inline src/components/CollectionDialog.jsx:103]: I'm going to leave this line untested. It does not actually make a lot of sense that there would be no `windowId`. The only way this line is ever executed would be a plugin that reuses this component.

**Review by marlo-longley — DISMISSED** [review]
This works for me, @lutzhelm. It addresses the issue found in PR #4154

**Review by marlo-longley — APPROVED** [review]
