### PR TITLE
Use css left to position the color pickers.

### LINKED ISSUE #1209: Annotation color pickers don't open in second slot
Those issues are also regressions.

Scenario to reproduce.

1. Open [](http://projectmirador.org/demo/)
2. Activate annotations inside slot 2
3. Choose a shape tool inside slot 2
4. Click border/fill color

Result: Nothing happens
Expected result: Color picker

### PR DESCRIPTION
**Pull request by jkeck**
It was previously using jQuery offset which styles the element relative to the document and not the canvas/window element.

This PR also uses outerWidth instead of width to account for element borders.

Closes #1209 

## 2nd Window
2nd-anno-style

## 1st Window
1st-anno-style

_To ensure that we don't break #1160, which is what this code was initially written to fix._

### CODE REVIEW

File: js/src/widgets/contextControls.js [hunk 1]
```diff
@@ -200,10 +200,7 @@
       pickerOffset=pickerContainer.offset(),
       windowWidth = this.state.windowsElements[this.windowId].width();
       if (pickerContainer.width() + pickerOffset.left > windowWidth) {
-        pickerContainer.offset({
-          top: pickerOffset.top,
-          left: windowWidth - (pickerContainer.width())
-        });
+        pickerContainer.css('left', windowWidth - (pickerContainer.outerWidth()));
```
Comment (jkeck) [inline js/src/widgets/contextControls.js]: I'm not sure this is ultimately the best way to position this, but I believe this is doing what the code was initially intending to do when written.

Comment (mejackreed) [inline js/src/widgets/contextControls.js]: Yep agree here. It's tough because positioning this is difficult. 👍
